hosts = [
  {
    :name => "hadoop001",
    :box => "generic/centos7",
    :ip => "192.168.31.101"
  },
  {
    :name => "hadoop002",
    :box => "generic/centos7",
    :ip => "192.168.31.102"
  },
  {
    :name => "hadoop003",
    :box => "generic/centos7",
    :ip => "192.168.31.103"
  }
  ]

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.box_check_update = false
  
  # 目录为上级目录
  config.vm.provider "virtualbox" do |_, vb|
    vb.vm.synced_folder "../", "/vagrant", type: "virtualbox"
  end

  hosts.each do |item|
    config.vm.define item[:name] do |host|
      host.vm.box = item[:box]
      host.vm.hostname = item[:name]
      host.vm.network :public_network, ip: item[:ip]
      host.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 2
        # v.gui = true
      end
    end
  end

  config.vm.provision "shell", inline: <<-SHELL
  echo root | passwd --stdin root
  sed -i 's/^#PermitRootLogin yes$/PermitRootLogin yes/' /etc/ssh/sshd_config
  sed -i 's/^PasswordAuthentication no$/PasswordAuthentication yes/' /etc/ssh/sshd_config
  systemctl restart sshd
  ip a
SHELL
end